config/routes.rb
Rails.application.routes.draw do
	resources :answers, only: [:new, :create, :show, :update, :destroy]

  resources :questions

  resources :users

  root to: "questions#index"

	get 'signup' => 'user#new'
		resources :users
  get 'posts/index'

  get 'posts/show'

  get '/login' => 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'


  get 'tags/new'

  get 'tags/index'

  get 'tags/show'

  get 'tags/update'

  get 'tags/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  belongs_to :tag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :tag
  has_many :answers

end

app/models/user.rb
class User < ApplicationRecord
  has_many :answers
  has_many :questions

  validates :displayname, presence: true
  validates :email, presence: true
  validates :password, presence: true
  has_secure_password
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
		@answer = Answer.new
  end

  def create
		p params
		if current_user
		@answer = Answer.new(answer_params)
		@answer[:question_id] = params["answer"]["question"].to_i
		#@answer = @question.answers.new(answer_params)
		@answer.user_id = current_user
		@answer[:rating] = 0
		@answer[:is_valid] = false
		@answer[:user_id] = current_user.id
		@answer[:tag_id] = 1
		
		if @answer.save
			redirect_to @answer, notice: 'Answer was successfully created.'
		else
			render 'new'
		end
			
		end
  end

  def show
    @answer = Answer.find(params[:id])
  end

  def update
		if @answer.update(answer_params)
			redirect_to @answer
		else
			render 'edit'
		end
  end

  def destroy
		@answer.destroy
	  redirect_to answers_show_path, notice: 'Answer was successfully deleted.'
  end

	private

	def set_answer
		@answer = Answer.find(params[:id])
	end

	def answer_params
      params.require(:answer).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user
 
  def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
 
  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.page(params[:page]).per(5)
  end

  def new
   @question = Question.new
  end

  def create
    if current_user
      @question = Question.new(question_params)
      @question[:user_id] = session[:user_id]
      @question[:rating] = 0

      #Look up tag id or create new tag in tag db
      tag = Tag.where({ name: params["question"]["tag_id"] }).first
      if(!tag.nil?)
        @question[:tag_id] = tag.id
      else
        newtag = Tag.new
        newtag.name = params["question"]["tag_id"]
        if newtag.save
          @question[:tag_id] = newtag.id
        else
          #Yeah... something went wrong
          @question[:tag_id] = 1
        end
      end

      if @question.save
        redirect_to @question
      else
        flash.now.alert = 'Error creating question. One or more fields were left blank or are invalid.'
        render "new"
      end

    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = @question.answers.build
#		@answer = Answer.new
		@answers = @question.answers
  end

  def update
  end

  def destroy
  end

  private

  def question_params
   params.require(:question).permit(:title, :content, :tag_id)
  end
 end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
      @user = User.find_by_email(params[:email])
      if @user && @user.authenticate(params[:password])
          session[:user_id] = @user.id
        redirect_to root_path
      else
        redirect_to '/login'
      end
   end

   def destroy
	  session[:user_id] = nil
	  redirect_to root_path
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def update
  end

  def destroy
  end

  private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:displayname, :email, :password, :password_confirmation)
    end


end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)

    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
			<h2><%= pluralize(answer.errors.count, "error") %>
			prohibited this book from being saved:</h2>
			
			<ul>
			<% answer.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
    </div>
  <% end %>

  <div class="field">
		<%= form.label :content %>
    <%= form.text_field :content, id: :answer_content %>
  </div>

  <%= form.hidden_field :question %>

  <div class="actions">
		<%= form.submit %>
  </div>

<% end %>

app/views/answers/create.html.erb
<h1>Create Answer</h1>

<%= render 'form', answer: @answer %>

<% link_to 'Back', answers_show_path %>

app/views/answers/destroy.html.erb
<h1>Answers#destroy</h1>
<p>Find me in app/views/answers/destroy.html.erb</p>

app/views/answers/new.html.erb
<h1 id="answers">New Answer</h1>

<%= render 'form', answer: @answer %>

<% link_to 'Back', answers_path %>


<footer>
           <div class="footrow">
                   <p>Copyright &copy; Rubeast Cohort 10 2017</p>
           </div>
       </footer>

app/views/answers/show.html.erb
 <h1>Answers</h1>
<hr />
<% @answers.each do |answer| %>
<!-- byebug -->
  <h2><%= question.title %></h2>
  <p>
  <%= answer.content %>
  <%= "is_valid:" + answer.is_valid.to_s %>
  <%= "user:" + answer.user_id.to_s %>
  </p>
<% end %>
<hr />
<%= paginate @questions %>
<%= page_entries_info @questions %>

<h1 id="answers">Answers#show</h1>
<p id="answers">Find me in app/views/answers/show.html.erb</p>

<footer>
	<div class="footrow">
		<p>Copyright &copy; Rubeast Cohort 10 2017</p>
	</div>
</footer>

app/views/answers/update.html.erb
<h1>Answers#update</h1>
<p>Find me in app/views/answers/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuestionBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<% if current_user %>
  <ul>
    <li><%= current_user.email %></li>
    <li><%= link_to "Log out", logout_path, method: "delete" %></li>
  </ul>
<% else %>
  <ul>
    <li><%= link_to "Login", login_path %></a></li>
    <li><%= link_to "Signup", new_user_path %></a></li>
  </ul>
<% end %>


  </head>

  <body>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/index.html.erb
<h1 id="index">Questions</h1>
<hr />
<% @questions.each do |question| %>
  <h2><%= link_to "#{question.title}", question_path(question)  %></h2>
  <p>
  <%= question.content %>
  <%= "tag_id:" + question.tag_id.to_s %>
  </p>
<% end %>
<hr />
<%= paginate @questions%>
<%= page_entries_info @questions %>














<!-- <footer>
           <div class="footrow">
                   <p>Copyright &copy; Rubeast Cohort 10 2017</p>
           </div>
       </footer> -->
>>>>>>> Stashed changes

app/views/questions/new.html.erb
<% if current_user %>
<h1 id="question-form-header">Create a new question please?</h1>

<button type="button"
onclick="document.getElementById('demo').innerHTML = Date()">
Click me to display Date and Time.</button>
<p id="demo"></p>

<div id=“question-form-wrapper“>
 <%= form_for @question do |f| %>

    <%= f.label :title, class: "form-group", id: "title" %>
    <%= f.text_field :title, class: "form-control"  %>

    <%= f.label :content, class: "form-group", id: "content" %>
    <%= f.text_field :content, class: "form-control" %>

   <%= f.label :user_id, class: "form-group", id: "user" %>
   <%= f.number_field :user_id, class: "form-control"  %>

   <%= f.label :tag_id, class: "form-group", id: "tag" %>
    <%= f.number_field :tag_id, class: "form-control"  %>

   <%= f.label :rating, class: "form-group", id: "rating" %>
    <%= f.number_field :rating, class: "form-control"  %>

   <%= f.submit "submit" %>
 <% end %>
</div>
<% else %>
  <h2>You must be logged in to create a new question</h2>
  <p><%= link_to 'Login', login_path %> | <%= link_to 'Register', new_user_path %></p>
<% end %>
 <footer>
    <div class="footrow">
      <p>Copyright &copy; Rubeast Cohort 10 2017</p>
    </div>
  </footer>

app/views/questions/show.html.erb
<%= link_to 'Back', url_for(:back) %>
<h1 id="answers">Questions#show</h1>
<p><%= @question.title %></p>
<p><%= @question.content %></p>
<p><% @question.answers.each do |answer| %>
  <%= answer.content %>
  <%= "Answer Correct:" + answer.is_valid.to_s %></p>
<%end%>

<footer>
  <div class="footrow">
    <p>Copyright &copy; Rubeast Cohort 10 2017</p>
  </div>
</footer>


<h3>Add an answer</h3>
<%= form_for @answer do |form| %>
<%= form.label :content %>
    <%= form.text_field :content, id: :answer_content %>

		<%= form.hidden_field :question, :value => @question.id %>

		<%= form.submit %>
<% end %>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>  </div>
    <%= form.text_field :displayname, id: :user_displayname %>


  <div class="field">
    <%= form.label :email %></div>
    <%= form.text_field :email, id: :user_email %>


  <div class="field">
    <%= form.label :password %>  </div>
    <%= form.password_field :password, id: :post_password %>


    <div class="field">
    <%= form.label :password_confirmation %>  </div>
    <%= form.password_field :password_confirmation, id: :post_password_confirmation %>
  <!-- </div> -->

<div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1 id="signUp">Sign up for Question Box please!</h1>
<button type="button"
onclick="document.getElementById('demo').innerHTML = Date()">
Click me to display Date and Time.</button>
<p id="demo"></p>

<%= render 'form', user: @user %>
<footer>
           <div class="footrow">
                   <p>Copyright &copy; Rubeast Cohort 10 2017</p>
           </div>
       </footer>

app/views/users/show.html.erb
<h1>Profile</h1>

<div class="col-sm-4">
  <span><%= @user.displayname %>
  <% if current_user && current_user.id == @user.id %>
    <%= link_to 'Edit', edit_user_path(@user) %>
  <% end %>
  </span>
	<%= @user.questions.each do |user| %>
		<% @question.title %>
		<% @question.content %>
		<% @question.answer %>
	<% end %>
</div>

<div class="col-sm-8">

</div>